FROM nvcr.io/nvidia/pytorch:23.10-py3

RUN pip3 install --upgrade pip setuptools wheel && \
    pip3 install --upgrade pip && \ 
    pip3 install \
        ipykernel \
        ipython \
        ipython-genutils \
        jupyter-client \
        jupyter-core \
        matplotlib \
        numpy \
        opencv-python==4.8.0.74 \
        Pillow \
        torch
